export const GROCERY_CATEGORIES = [
  "Produce",
  "Meat & Seafood",
  "Dairy & Eggs",
  "Bakery",
  "Frozen",
  "Pantry",
  "Snacks",
  "Beverages",
  "Household",
  "Other",
];

// NOTE: The order of keys in this object determines the matching priority.
// We put "Pantry" and "Frozen" early to catch things like "Frozen Peas" or "Garlic Powder"
// before they get caught by "Produce".
// NOTE: The order of this array determines the matching priority.
// We put "Pantry" and "Frozen" early to catch things like "Frozen Peas" or "Garlic Powder"
// before they get caught by "Produce".
const CATEGORY_RULES: { category: string; keywords: string[] }[] = [
  {
    category: "Frozen",
    keywords: [
      "frozen",
      "ice cream",
      "sorbet",
      "gelato",
      "popsicle",
      "pizza",
      "waffle",
      "nugget",
      "tater tot",
      "fries",
      "hash brown",
      "tv dinner",
      "steamfresh",
      "hot pocket",
      "bagel bite",
      "cool whip",
      "ice",
    ],
  },
  {
    category: "Bakery",
    keywords: [
      "bread",
      "loaf",
      "bun",
      "roll",
      "bagel",
      "croissant",
      "muffin",
      "scone",
      "donut",
      "doughnut",
      "danish",
      "pastry",
      "cake",
      "cupcake",
      "pie",
      "tart",
      "brownie",
      "cookie",
      "biscuit",
      "tortilla",
      "pita",
      "flatbread",
      "naan",
      "wrap",
      "sourdough",
      "rye",
      "wheat",
      "white bread",
      "baguette",
      "focaccia",
      "challah",
      "ciabatta",
      "english muffin",
      "toast",
    ],
  },
  {
    category: "Meat & Seafood",
    keywords: [
      "chicken",
      "breast",
      "thigh",
      "wing",
      "drumstick",
      "turkey",
      "beef",
      "steak",
      "ground beef",
      "roast",
      "ribeye",
      "sirloin",
      "filet",
      "brisket",
      "pork",
      "chop",
      "loin",
      "bacon",
      "ham",
      "sausage",
      "salami",
      "pepperoni",
      "prosciutto",
      "deli",
      "hot dog",
      "frank",
      "bratwurst",
      "lamb",
      "veal",
      "fish",
      "salmon",
      "tuna",
      "cod",
      "tilapia",
      "halibut",
      "shrimp",
      "prawn",
      "crab",
      "lobster",
      "scallop",
      "clam",
      "oyster",
      "mussel",
      "calamari",
      "anchovy",
      "sardine",
      "meatball",
      "patty",
      "burger",
    ],
  },
  {
    category: "Dairy & Eggs",
    keywords: [
      "milk",
      "cream",
      "half and half",
      "half & half",
      "butter",
      "margarine",
      "egg",
      "cheese",
      "cheddar",
      "mozzarella",
      "parmesan",
      "brie",
      "feta",
      "gouda",
      "swiss",
      "provolone",
      "ricotta",
      "yogurt",
      "yoghurt",
      "kefir",
      "sour cream",
      "cottage cheese",
      "whipped cream",
      "pudding",
      "custard",
      "ghee",
      "paneer",
      "mascarpone",
      "colby",
      "monterey jack",
      "blue cheese",
      "creamer",
    ],
  },
  {
    category: "Pantry",
    keywords: [
      // Baking
      "flour",
      "sugar",
      "baking",
      "yeast",
      "vanilla",
      "cocoa",
      "chocolate chip",
      "spray",
      "crisco",
      "lard",
      "cornstarch",
      "syrup",
      "honey",
      "molasses",
      "sweetener",
      "stevia",
      // Grains & Pasta
      "rice",
      "quinoa",
      "couscous",
      "barley",
      "oat",
      "oatmeal",
      "cereal",
      "granola",
      "pasta",
      "noodle",
      "spaghetti",
      "penne",
      "macaroni",
      "fettuccine",
      "lasagna",
      "ramen",
      "box",
      "mix",
      "taco shell",
      "breadcrumbs",
      // Canned/Jarred
      "can",
      "jar",
      "soup",
      "broth",
      "stock",
      "bouillon",
      "paste",
      "sauce",
      "marinara",
      "alfredo",
      "salsa",
      "ketchup",
      "mustard",
      "mayo",
      "mayonnaise",
      "bbq",
      "barbecue",
      "ranch",
      "dressing",
      "vinegar",
      "oil",
      "olive oil",
      "vegetable oil",
      "canola",
      "soy sauce",
      "teriyaki",
      "sriracha",
      "hot sauce",
      "peanut butter",
      "jelly",
      "jam",
      "preserve",
      "pickle",
      "olive",
      "caper",
      // Spices & Seasoning (Detailed)
      "salt",
      "pepper",
      "spice",
      "seasoning",
      "powder",
      "dried",
      "rub",
      "cumin",
      "paprika",
      "cinnamon",
      "nutmeg",
      "clove",
      "ginger",
      "turmeric",
      "curry",
      "coriander",
      "cardamom",
      "chili",
      "cayenne",
      "oregano",
      "basil",
      "thyme",
      "rosemary",
      "sage",
      "bay leaf",
      "parsley",
      "dill",
      "fennel",
      "mustard seed",
      "poppy",
      "sesame",
      "extract",
    ],
  },
  {
    category: "Produce",
    keywords: [
      // Fruits
      "apple",
      "banana",
      "orange",
      "grape",
      "berry",
      "strawberry",
      "blueberry",
      "raspberry",
      "blackberry",
      "melon",
      "watermelon",
      "cantaloupe",
      "honeydew",
      "lemon",
      "lime",
      "citrus",
      "peach",
      "pear",
      "plum",
      "nectarine",
      "apricot",
      "cherry",
      "mango",
      "pineapple",
      "kiwi",
      "avocado",
      "pomegranate",
      "fig",
      "date",
      "fruit",
      // Veggies
      "tomato",
      "cucumber",
      "pepper",
      "jalapeno",
      "habanero",
      "lettuce",
      "spinach",
      "kale",
      "arugula",
      "cabbage",
      "broccoli",
      "cauliflower",
      "carrot",
      "celery",
      "onion",
      "garlic",
      "shallot",
      "leek",
      "scallion",
      "green onion",
      "potato",
      "yam",
      "sweet potato",
      "squash",
      "zucchini",
      "pumpkin",
      "corn",
      "mushroom",
      "asparagus",
      "bean",
      "pea",
      "radish",
      "beet",
      "ginger",
      "root",
      "sprout",
      "salad",
      // Fresh Herbs (If not caught by Pantry "dried")
      "herb",
      "basil",
      "cilantro",
      "parsley",
      "dill",
      "rosemary",
      "thyme",
      "mint",
      "sage",
      "chive",
      "lemongrass",
    ],
  },
  {
    category: "Beverages",
    keywords: [
      "water",
      "soda",
      "coke",
      "pepsi",
      "sprite",
      "dr pepper",
      "pop",
      "juice",
      "lemonade",
      "tea",
      "coffee",
      "espresso",
      "latte",
      "k-cup",
      "beer",
      "wine",
      "liquor",
      "vodka",
      "whiskey",
      "rum",
      "gin",
      "tequila",
      "alcohol",
      "cider",
      "energy drink",
      "sports drink",
      "gatorade",
      "powerade",
      "seltzer",
      "sparkling",
      "drink",
    ],
  },
  {
    category: "Snacks",
    keywords: [
      "chip",
      "potato chip",
      "tortilla chip",
      "dorito",
      "cheeto",
      "pretzel",
      "popcorn",
      "cracker",
      "goldfish",
      "cheez-it",
      "nut",
      "peanut",
      "almond",
      "cashew",
      "pecan",
      "walnut",
      "pistachio",
      "mix",
      "trail mix",
      "bar",
      "granola bar",
      "protein bar",
      "jerky",
      "slim jim",
      "fruit snack",
      "gummy",
      "candy",
      "chocolate",
      "gum",
      "mint",
      "cookie",
      "wafer",
      "snack",
    ],
  },
  {
    category: "Household",
    keywords: [
      "paper",
      "soap",
      "cleaner",
      "detergent",
      "trash",
      "foil",
      "wrap",
      "ziploc",
      "tissue",
      "napkin",
      "sponge",
      "bleach",
      "wipes",
      "shampoo",
      "conditioner",
      "toothpaste",
      "floss",
      "deodorant",
      "lotion",
      "vitamin",
      "medicine",
      "battery",
      "bulb",
    ],
  },
];

export function inferCategory(itemName: string): string {
  const lowerName = itemName.toLowerCase().trim();

  for (const rule of CATEGORY_RULES) {
    // Check if the item name contains any of the keywords
    // We use a regex that allows for optional pluralization (s or es) at the end of the keyword
    // e.g. "apple" matches "apples", "box" matches "boxes"
    if (
      rule.keywords.some((k) =>
        new RegExp(`\\b${k}(?:es|s)?\\b`, "i").test(lowerName),
      )
    ) {
      return rule.category;
    }
  }

  return "Other";
}
