export const GROCERY_CATEGORIES = [
  "Produce",
  "Meat & Seafood",
  "Dairy & Eggs",
  "Bakery",
  "Frozen",
  "Pantry",
  "Snacks",
  "Beverages",
  "Household",
  "Other",
];

// NOTE: The order of keys in this object determines the matching priority.
// We put "Pantry" and "Frozen" early to catch things like "Frozen Peas" or "Garlic Powder"
// before they get caught by "Produce".
const KEYWORD_MAP: Record<string, string[]> = {
  Frozen: [
    "frozen",
    "ice cream",
    "sorbet",
    "gelato",
    "popsicle",
    "pizza",
    "waffle",
    "nugget",
    "tater tot",
    "fries",
    "hash brown",
    "tv dinner",
    "steamfresh",
    "hot pocket",
    "bagel bite",
    "cool whip",
    "ice",
  ],
  Bakery: [
    "bread",
    "loaf",
    "bun",
    "roll",
    "bagel",
    "croissant",
    "muffin",
    "scone",
    "donut",
    "doughnut",
    "danish",
    "pastry",
    "cake",
    "cupcake",
    "pie",
    "tart",
    "brownie",
    "cookie",
    "biscuit",
    "tortilla",
    "pita",
    "flatbread",
    "naan",
    "wrap",
    "sourdough",
    "rye",
    "wheat",
    "white bread",
    "baguette",
    "focaccia",
    "challah",
    "ciabatta",
    "english muffin",
  ],
  "Meat & Seafood": [
    "chicken",
    "breast",
    "thigh",
    "wing",
    "drumstick",
    "turkey",
    "beef",
    "steak",
    "ground beef",
    "roast",
    "ribeye",
    "sirloin",
    "filet",
    "brisket",
    "pork",
    "chop",
    "loin",
    "bacon",
    "ham",
    "sausage",
    "salami",
    "pepperoni",
    "prosciutto",
    "deli",
    "hot dog",
    "frank",
    "bratwurst",
    "lamb",
    "veal",
    "fish",
    "salmon",
    "tuna",
    "cod",
    "tilapia",
    "halibut",
    "shrimp",
    "prawn",
    "crab",
    "lobster",
    "scallop",
    "clam",
    "oyster",
    "mussel",
    "calamari",
    "anchovy",
    "sardine",
    "meatball",
    "patty",
  ],
  "Dairy & Eggs": [
    "milk",
    "cream",
    "half and half",
    "half & half",
    "butter",
    "margarine",
    "egg",
    "cheese",
    "cheddar",
    "mozzarella",
    "parmesan",
    "brie",
    "feta",
    "gouda",
    "swiss",
    "provolone",
    "ricotta",
    "yogurt",
    "yoghurt",
    "kefir",
    "sour cream",
    "cottage cheese",
    "whipped cream",
    "pudding",
    "custard",
    "ghee",
    "paneer",
    "mascarpone",
    "colby",
    "monterey jack",
    "blue cheese",
  ],
  // Check Pantry BEFORE Produce to catch "Dried Basil" or "Onion Powder"
  Pantry: [
    // Baking
    "flour",
    "sugar",
    "baking",
    "yeast",
    "vanilla",
    "cocoa",
    "chocolate chip",
    "spray",
    "crisco",
    "lard",
    "cornstarch",
    "syrup",
    "honey",
    "molasses",
    // Grains & Pasta
    "rice",
    "quinoa",
    "couscous",
    "barley",
    "oat",
    "oatmeal",
    "cereal",
    "granola",
    "pasta",
    "noodle",
    "spaghetti",
    "penne",
    "macaroni",
    "fettuccine",
    "lasagna",
    "ramen",
    "box",
    "mix",
    "taco shell",
    "breadcrumbs",
    // Canned/Jarred
    "can",
    "jar",
    "soup",
    "broth",
    "stock",
    "bouillon",
    "paste",
    "sauce",
    "marinara",
    "alfredo",
    "salsa",
    "ketchup",
    "mustard",
    "mayo",
    "mayonnaise",
    "bbq",
    "barbecue",
    "ranch",
    "dressing",
    "vinegar",
    "oil",
    "olive oil",
    "vegetable oil",
    "canola",
    "soy sauce",
    "teriyaki",
    "sriracha",
    "hot sauce",
    "peanut butter",
    "jelly",
    "jam",
    "preserve",
    "pickle",
    "olive",
    "caper",
    // Spices & Seasoning (Detailed)
    "salt",
    "pepper",
    "spice",
    "seasoning",
    "powder",
    "dried",
    "rub",
    "cumin",
    "paprika",
    "cinnamon",
    "nutmeg",
    "clove",
    "ginger",
    "turmeric",
    "curry",
    "coriander",
    "cardamom",
    "chili",
    "cayenne",
    "oregano",
    "basil",
    "thyme",
    "rosemary",
    "sage",
    "bay leaf",
    "parsley",
    "dill",
    "fennel",
    "mustard seed",
    "poppy",
    "sesame",
  ],
  Produce: [
    // Fruits
    "apple",
    "banana",
    "orange",
    "grape",
    "berry",
    "strawberry",
    "blueberry",
    "raspberry",
    "blackberry",
    "melon",
    "watermelon",
    "cantaloupe",
    "honeydew",
    "lemon",
    "lime",
    "citrus",
    "peach",
    "pear",
    "plum",
    "nectarine",
    "apricot",
    "cherry",
    "mango",
    "pineapple",
    "kiwi",
    "avocado",
    "pomegranate",
    "fig",
    "date",
    // Veggies
    "tomato",
    "cucumber",
    "pepper",
    "jalapeno",
    "habanero",
    "lettuce",
    "spinach",
    "kale",
    "arugula",
    "cabbage",
    "broccoli",
    "cauliflower",
    "carrot",
    "celery",
    "onion",
    "garlic",
    "shallot",
    "leek",
    "scallion",
    "green onion",
    "potato",
    "yam",
    "sweet potato",
    "squash",
    "zucchini",
    "pumpkin",
    "corn",
    "mushroom",
    "asparagus",
    "bean",
    "pea",
    "radish",
    "beet",
    "ginger",
    "root",
    "sprout",
    // Fresh Herbs (If not caught by Pantry "dried")
    "herb",
    "basil",
    "cilantro",
    "parsley",
    "dill",
    "rosemary",
    "thyme",
    "mint",
    "sage",
    "chive",
    "lemongrass",
  ],
  Beverages: [
    "water",
    "soda",
    "coke",
    "pepsi",
    "sprite",
    "dr pepper",
    "pop",
    "juice",
    "lemonade",
    "tea",
    "coffee",
    "espresso",
    "latte",
    "k-cup",
    "beer",
    "wine",
    "liquor",
    "vodka",
    "whiskey",
    "rum",
    "gin",
    "tequila",
    "alcohol",
    "cider",
    "energy drink",
    "sports drink",
    "gatorade",
    "powerade",
    "seltzer",
    "sparkling",
  ],
  Snacks: [
    "chip",
    "potato chip",
    "tortilla chip",
    "dorito",
    "cheeto",
    "pretzel",
    "popcorn",
    "cracker",
    "goldfish",
    "cheez-it",
    "nut",
    "peanut",
    "almond",
    "cashew",
    "pecan",
    "walnut",
    "pistachio",
    "mix",
    "trail mix",
    "bar",
    "granola bar",
    "protein bar",
    "jerky",
    "slim jim",
    "fruit snack",
    "gummy",
    "candy",
    "chocolate",
    "gum",
    "mint",
    "cookie",
    "wafer",
  ],
  Household: [
    "paper",
    "soap",
    "cleaner",
    "detergent",
    "trash",
    "foil",
    "wrap",
    "ziploc",
    "tissue",
    "napkin",
    "sponge",
    "bleach",
    "wipes",
    "shampoo",
    "conditioner",
    "toothpaste",
    "floss",
    "deodorant",
    "lotion",
    "vitamin",
    "medicine",
  ],
};

export function inferCategory(itemName: string): string {
  const lowerName = itemName.toLowerCase().trim();

  // 1. Loop through our map
  for (const [category, keywords] of Object.entries(KEYWORD_MAP)) {
    // 2. Check if the item name contains any of the keywords
    if (keywords.some((k) => new RegExp(`\\b${k}\\b`).test(lowerName))) {
      return category;
    }
  }

  return "Other";
}
